name: Validate Renovate Config

on:
  push:
    branches:
      - main
    paths:
      - renovate-config.json
  pull_request:
    branches:
      - main
    paths:
      - renovate-config.json

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate renovate-config.json against schema
        uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7 # v3.1.1
        with:
          file: renovate-config.json
          schema: https://docs.renovatebot.com/renovate-schema.json
